### ISSUE TITLE
Stop using the keyring module

### ISSUE THREAD

**Issue by r-darwish** [r-darwish/pushbullet-cli#22]

**Comment by iLoveTux** [comment]
Is there any reason you would like to stop using this module? I ask because I use it in other places and if there are major concerns about using it I would like to know, also you will probably be seeing a bit more of me as I am starting to use pushbullet for our company's alerting system.

**Comment by r-darwish** [comment]
I'm actually still debating about this. When the keyring module can't access the operating system keyring, which either happens when used in Linux without any desktop, or when used under GNOME/Unity in a virtualenv that doesn't use have pygobject, all it does is to store the token as plaintext in a file accessible only by the user runnning pushbullet-cli, which is what I done before I started using this module. So we get this extra layer of security only when using OS X, Windows or a non-headless Linux not through a virtualenv, and this extra layer of security only protects your token from someone having a physical access to your machine.
Furthermore, as I see it, most software that saves user tokens (specifically, softwares that save your github token) doesn't use a keyring for that, as stolen tokens can be easily reset.
Like I said, I'm still debating, so I'll leave this open at the moment for more opinions.

**Comment by iLoveTux** [comment]
Just my two cents, but based on what I read [here](http://stackoverflow.com/questions/7014953/i-need-to-securely-store-a-username-and-password-in-python-what-are-my-options) (I had to do some research as crypto is not my area of expertise) I believe you are using the best option for the following reasons:

1. Despite the security holes you mention, in most cases, there is an extra layer of security and when there isn't it falls back to your previous solution anyway.
2. Any other solutions I see would either require you to enter a password for each invocation (I discount this option because you have a comment in your source which reads `# 
The pycrypto encrypted keyring asks for a password in every launch. This is unacceptable.`) or use a key sitting on the filesystem somewhere and casual inspection of the source would allow an attacker to easily bypass any encryption you've implemented.
3. While it's true that tokens can easily be reset, this key grants some pretty significant permissions on a number of devices (SMS, files, contacts, identity, accounts, etc) I would personally like this token to be protected a little better than my github token as the ramifications of what an attacker could do with access to all of my devices vs what they could do with my github account (or any single online account) are much worse.

But like I said, this is not my area of expertise.

**Comment by r-darwish** [comment]
I guess I'm convinced then. Thanks for the two cents
